CREATE SEQUENCE IF NOT EXISTS usuario_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE IF NOT EXISTS usuario (
	id BIGINT PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	senha VARCHAR(150) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS permissao_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
  
CREATE TABLE IF NOT EXISTS permissao (
	id BIGINT PRIMARY KEY,
	descricao VARCHAR(50) NOT NULL
) ;

CREATE SEQUENCE IF NOT EXISTS usuario_permissao_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
  
CREATE TABLE IF NOT EXISTS usuario_permissao (
	codigo_usuario BIGINT NOT NULL,
	codigo_permissao BIGINT NOT NULL,
	PRIMARY KEY (codigo_usuario, codigo_permissao),
	FOREIGN KEY (codigo_usuario) REFERENCES usuario(id),
	FOREIGN KEY (codigo_permissao) REFERENCES permissao(id)
) ;